### ISSUE TITLE
[1.16.1] Won't load on latest version of Forge.

### ISSUE THREAD

**Issue by Gbergz** [Shadows-of-Fire/Toast-Control#16]
Title^

**Minecraft:** 1.16.1
**Forge:** 32.0.97
**Mod Version:** 4.0.1
**Placebo Version:** 4.0.1

**Logs:** 
https://hastebin.com/epojarihob.sql

**Screenshot:**
![image](https://user-images.githubusercontent.com/26634554/88799971-a2d78b80-d1a7-11ea-9051-f611081eaf6a.png)

**-** Gbergz

**Comment by LiskoSlayer63** [comment]
I can confirm this too, tried today with:

**Minecraft:** 1.16.1
**Forge:** 32.0.97
**Mod Version:** 4.0.1
**Placebo Version:** 4.0.1

**Log:**
_I'd upload it, but really can't find anything beside the normal startup log. Any help on this?_

**Comment by tyrus7141** [comment]
Here is a full error log.

[11:34:03] [modloading-worker-3/ERROR]: Failed to create mod instance. ModID: toastcontrol, class shadows.toaster.ToastLoader
java.lang.IllegalArgumentException: Method public void shadows.toaster.ToastControl.clientTick(net.minecraftforge.event.TickEvent$ClientTickEvent) has @SubscribeEvent annotation, but takes an argument that is not a subtype of the base type interface net.minecraftforge.fml.event.lifecycle.IModBusEvent: class net.minecraftforge.event.TickEvent$ClientTickEvent
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:145) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$null$6(EventBus.java:98) ~[eventbus-3.0.3-service.jar:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:98) ~[eventbus-3.0.3-service.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_261]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:94) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-3.0.3-service.jar:?]
	at shadows.toaster.ToastLoader.<init>(ToastLoader.java:23) ~[?:4.0.1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:136) ~[?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]
[11:34:03] [modloading-worker-3/ERROR]: An error occurred while dispatching event CONSTRUCT to toastcontrol
[11:34:03] [modloading-worker-3/FATAL]: EventBus 34 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.afterEvent(FMLModContainer.java:123) ~[?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]

**Comment by xdjoshuaaz** [comment]
@Shadows-of-Fire I've made a PR that fixes this on 32.0.96 and above. Could you review please?

**Comment by Gbergz** [comment]
Saw you released a new version this one [v4.1.0](https://www.curseforge.com/minecraft/mc-mods/toast-control/files/3024516) but I'm still getting the error shown on the picture on the initial report, I'm using Forge 32.0.106.
Using newest placebo aswell: [v4.1.0](https://www.curseforge.com/minecraft/mc-mods/placebo/files/3024512)

**Comment by Shadows-of-Fire** [comment]
That file appears to have not actually been the new file, it should be archived/replaced as soon as cf approves the new copy

**Comment by ProsperCraft** [comment]
Confirmed fixed, you have to manually update as Twitch is currently downloading the old version by default.
