### ISSUE TITLE
Log spam when hiding Crafting advancements [1.12.2]

### ISSUE THREAD

**Issue by Shibva** [Shadows-of-Fire/Toast-Control#21]
was wondering if there was a way to prevent it from doing that

Example of error in log

Parsing error loading built-in advancement biomesoplenty:recipes/decorations/crafting_table_from_bop_wood
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:crafting_table'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171)
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:439)
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:455)
	at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:203)
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50)
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492)
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:517)
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:537)
	at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1381)
	at net.minecraftforge.common.ForgeHooks$$Lambda$7979/2055297078.apply(Unknown Source)
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833)
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1359)
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1326)
	at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:69)
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60)
	at net.minecraft.world.WorldServer.init(WorldServer.java:156)
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:133)
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Shadows-of-Fire** [comment]
This is an advancement loading error, it has nothing to do with TC and TC can't do anything about it
